Homework week 1 Zekai Koc
HackYourHomework/Homework-class43 pull request #36
Opened 2023-05-07 18:24 UTC by Zekai-Koc

Hi. I have multiple github accounts and i forked the repo with a different account named "Michael".  that is my alias.

2023-05-08 12:12 UTC, chrisdoc requested changes
Two minor things regarding the excess try catch

2023-05-08 12:12 UTC, chrisdoc commented on 3-UsingAPIs/Week1/homework/ex1-johnWho.js
> +    try {
@Zekai-Koc this `try {...} catch(e) {...}` block is needed here

2023-05-08 12:12 UTC, chrisdoc commented on 3-UsingAPIs/Week1/homework/ex2-checkDoubleDigits.js
> +    try {
Again this `try {...} catch(e) {...} block` is needed here as there is nothing that could throw an exception inside

2023-05-08 12:30 UTC, Zekai-Koc commented on 3-UsingAPIs/Week1/homework/ex2-checkDoubleDigits.js
> +    try {
as a best practice i prefer try/catch blocks. 
btw, i had them in the other exercises as well but tester made me delete them all. :)
should i delete or keep?

2023-05-08 12:30 UTC, Zekai-Koc commented on 3-UsingAPIs/Week1/homework/ex1-johnWho.js
> +    try {
as a best practice i prefer try/catch blocks. 
btw, i had them in the other exercises as well but tester made me delete them all. :)
should i delete or keep?

2023-05-08 14:25 UTC, chrisdoc commented on 3-UsingAPIs/Week1/homework/ex1-johnWho.js
> +    try {
If the code doesn't throw any exceptions then adding additional try / catch does not have any purpose, hence I would remove them as they don't do anything in this case :)

2023-05-09 08:48 UTC, chrisdoc approved these changes

2023-05-09 14:47 UTC, chrisdoc commented
LGTM 🚀 Great work

2023-05-15 14:57 UTC, closed without merging